services:
  db:
    image: postgres:18

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: log_ingestion

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d log_ingestion"]
      interval: 5s
      timeout: 5s
      retries: 5

    cpus: 1.0
    mem_limit: 1g

volumes:
  postgres_data:
