//keep logs
export async function up(pgm) {
  pgm.sql(`
    ALTER TABLE logs
    RENAME TO logs_unpartitioned;

    ALTER TABLE logs_unpartitioned
    RENAME CONSTRAINT logs_pkey
    TO logs_unpartitioned_pkey;

    ALTER INDEX IF EXISTS logs_timestamp_id_idx
    RENAME TO logs_unpartitioned_timestamp_id_idx;


    CREATE TABLE logs (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY,
      timestamp TIMESTAMPTZ NOT NULL,
      level TEXT NOT NULL,
      service TEXT NOT NULL,
      message TEXT NOT NULL,
      attributes JSONB NOT NULL DEFAULT '{}',

      PRIMARY KEY (timestamp, id)
    )
    PARTITION BY RANGE (timestamp);


    DO $$
    DECLARE
      partition_date DATE;
      partition_name TEXT;
      next_date DATE;
    BEGIN
      FOR partition_date IN
        SELECT DISTINCT day_value
        FROM (
          SELECT
            (timestamp AT TIME ZONE 'UTC')::date
            AS day_value
          FROM logs_unpartitioned

          UNION

          SELECT
            generate_series(
              CURRENT_DATE - 30,
              CURRENT_DATE + 2,
              INTERVAL '1 day'
            )::date
        ) days
        ORDER BY day_value
      LOOP
        partition_name :=
          'logs_' || to_char(
            partition_date,
            'YYYYMMDD'
          );

        next_date := partition_date + 1;

        EXECUTE format(
          'CREATE TABLE %I
           PARTITION OF logs
           FOR VALUES FROM (%L)
           TO (%L)',
          partition_name,
          partition_date::text
            || ' 00:00:00+00',
          next_date::text
            || ' 00:00:00+00'
        );
      END LOOP;
    END $$;


    CREATE TABLE logs_default
    PARTITION OF logs DEFAULT;


    INSERT INTO logs (
      id,
      timestamp,
      level,
      service,
      message,
      attributes
    )
    SELECT
      id,
      timestamp,
      level,
      service,
      message,
      attributes
    FROM logs_unpartitioned;


    SELECT setval(
      pg_get_serial_sequence('logs', 'id'),
      COALESCE(
        (SELECT MAX(id) FROM logs),
        1
      ),
      EXISTS (
        SELECT 1 FROM logs
      )
    );


    DROP TABLE logs_unpartitioned;
  `);
}

export async function down(pgm) {
  pgm.sql(`
    CREATE TABLE logs_flat (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
      timestamp TIMESTAMPTZ NOT NULL,
      level TEXT NOT NULL,
      service TEXT NOT NULL,
      message TEXT NOT NULL,
      attributes JSONB NOT NULL DEFAULT '{}'
    );

    INSERT INTO logs_flat (
      id,
      timestamp,
      level,
      service,
      message,
      attributes
    )
    SELECT
      id,
      timestamp,
      level,
      service,
      message,
      attributes
    FROM logs;

    SELECT setval(
      pg_get_serial_sequence(
        'logs_flat',
        'id'
      ),
      COALESCE(
        (SELECT MAX(id) FROM logs_flat),
        1
      ),
      EXISTS (
        SELECT 1 FROM logs_flat
      )
    );

    DROP TABLE logs CASCADE;

    ALTER TABLE logs_flat
    RENAME TO logs;

    CREATE INDEX logs_timestamp_id_idx
    ON logs (timestamp DESC, id DESC);
  `);
}
